import {
  IconButton,
  VStack,
  useColorMode,
  Heading,
  Box,
  Center,
} from "@chakra-ui/react";
import { FaMoon, FaSun } from "react-icons/fa";
import Head from "next/head";
import Image from "next/image";
import TodoList from "@/components/TodoList";
import AddTodo from "@/components/AddTodo";

export default function Home() {
  const { colorMode, toggleColorMode } = useColorMode();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/thirteen.svg" />
      </Head>
      <Box>
        <VStack p={4}>
          <IconButton
            aria-label={"icon"}
            icon={colorMode === "light" ? <FaMoon /> : <FaSun />}
            size={"lg"}
            alignSelf="flex-end"
            onClick={toggleColorMode}
          />

          <Heading
            fontWeight={"extrabold"}
            size="2xl"
            bgGradient={"linear(to-r, green.500, green.300, blue.500)"}
            bgClip="text"
          >
            Todo Application
          </Heading>
        </VStack>
        <Center>
          <TodoList />
        </Center>
        <Center>
          <AddTodo />
        </Center>
      </Box>
    </>
  );
}
